const allPracticeData = {
  // Polity: {
  //   "historical background and Making of Constitution": [],
  //   "Salient Features of Constitution": [],
  //   legislature: [],
  //   executive: [],
  //   judiciary: [],
  //   "local self government": [],
  //   governance: [],
  //   "constitutional and non constitutional bodies": [],
  //   "judicial & Quasi Judicial bodies": [],
  //   IR: [],
  // },
  // History: {
  //   Modern_History: [],
  //   Ancient_History: [],
  //   Medieval_History: [],
  //   Art_and_Culture: [],
  // },
  // Geography: {
  //   Indian_Geography: [],
  //   World_Geography: [],
  // },
  // Environment_Ecology: {
  //   environment_and_ecology: [],
  // },
  // Economy: {
  //   "pillar 1 Money and Banking": [],
  //   "pillar 2 Budget and Taxation": [],
  //   "pillar 3 International Economics": [],
  //   "pillar 4 Agriculture and Industry": [],
  //   "pillar 5 Infrastructure": [],
  //   "pillar 6 Services Sector": [],
  // },
  // "Science and Tech": {
  //   Biotechnology: [],
  //   Defence_Technology: [],
  //   Space_Science: [],
  //   IT_and_Communication_Technology: [],
  //   Energy: [],
  //   Miscellaneous_Science_Tech: [],
  //   Physics: [],
  //   Chemistry: [],
  //   Biology: [],
  // },
  PYQ: {
    Polity: [],
    "Modern History": [],
    "Ancient History": [],
    "Medieval History": [],
    "World Geography": [],
    "Indian Geography": [],
    "Environment and Ecology": [],
    IR: [],
    Economy: [],
    "Science and Tech": [],
  },
};
