// // quizData.js

// const allQuizData = {
//     "SFG Test": typeof sfgData !== 'undefined' ? sfgData : {},
//     "Murnal Weekely Test": typeof murnalData !== 'undefined' ? murnalData : {},
//     "Sathvik Bhan Monthly CA Test": typeof sathvikBhanCaData !== 'undefined' ? sathvikBhanCaData : {},
//     "Year Wise PYQ": typeof yearWiseData !== 'undefined' ? yearWiseData : {},
//     "Modern History PYQ": typeof modernHistoryData !== 'undefined' ? modernHistoryData : {},
//     "Ancient History PYQ": typeof ancientHistoryData !== 'undefined' ? ancientHistoryData : {},
//     "Medieval History PYQ": typeof medievalHistoryData !== 'undefined' ? medievalHistoryData : {},
//     "Art and Culture PYQ": typeof artCultureData !== 'undefined' ? artCultureData : {},
//     "World Geography PYQ": typeof worldGeographyData !== 'undefined' ? worldGeographyData : {},
//     "Indian Geography PYQ": typeof indianGeographyData !== 'undefined' ? indianGeographyData : {},
//     "Environment and Ecology PYQ": typeof environmentData !== 'undefined' ? environmentData : {},
//     "Polity PYQ": typeof polityData !== 'undefined' ? polityData : {},
//     "IR PYQ": typeof irData !== 'undefined' ? irData : {},
//     "Economy PYQ": typeof economyData !== 'undefined' ? economyData : {},
//     "Science and Tech PYQ": typeof scienceTechData !== 'undefined' ? scienceTechData : {}
// };

// quizData.js - Manifest of Subjects and Chapters
/* ==========================================================
   quizData.js - Manifest of Subjects and Chapters
   ==========================================================
   This file contains the structure for the Subject/Chapter 
   selection screens. Question arrays are left empty ([]) 
   as the actual data is lazy-loaded from Firestore.
   ========================================================== */

const allQuizData = {
  "SFG Test": {
    "Test-1-Polity (321101)": [],
    "Test-2-Polity (321102)": [],
    "Test-3-Polity (321103)": [],
  },
  "Murnal Weekely Test": {
    Pillar_1A1_HDT_Money_Barter_to_Bitcoins: [],
    "Pillar_1A2_Monetary Policy": [],
    "Pillar_1B1_Classificaiton of Bank NBFC": [],
    "Pillar_1B2_NPA and Other Burning Issues": [],
    Pillar_1C1_Bond_Market_Money_Market_WMA: [],
    Pillar_1C2_SEBI_Sharemarket_ETF_Derivatives: [],
    "Pillar_1C3_Corporate Governance & Companies Act": [],
    Pillar_1D1_Insurance: [],
    "Pillar_1D2_Pension & 1D3_Financial inclusion": [],
    "Pillar_2A1_Budget Intro & Direct Taxes": [],
    "Pillar_2A2_GST & Indirect Taxes": [],
    Pillar_2B_Finance_Commission: [],
    Pillar_2C_Black_Money_Subsidies: [],
    Pillar_2D_FRBM_Deficit_Disinvestment: [],
    Pillar_3A_BoP_Import_Export_FDI_FPI: [],
    Pillar_3B_Currency_Exchange: [],
    "Pillar3C_International_Organisations & Agreements": [],
    Pillar4A1_AGRO_INPUT: [],
    Pillar4A2_AGRO_OUTPUT: [],
    "Pillar 4B_Mfg, Services, E-Commerce, MSME, IPR": [],
    Pillar_4C_NITI_PC_FYP_Unemployment: [],
    Pillar_4D_GDP: [],
    Pillar_4E_Inflation: [],
    "Pillar_5A_Infra-Energy": [],
    "Pillar_5B_Infra-Transport": [],
    "Pillar_5C_Infra-Rural to Communication": [],
    Pillar_6A_Health_Hunger: [],
    "Pillar_6B: Edu & Skill": [],
    "Pillar_6C_HRD-Poverty": [],
    "Pillar_6D_HRD-Weaker Section": [],
    "Pillar_6E_HRD-HDI_SDG": [],
  },
  "Sathvik Bhan Monthly CA Test": {
    "July 2025": [],
    "August 2025": [],
    "September 2025": [],
    "October 2025": [],
  },
  "Year Wise PYQ": {
    "UPSC CSE 2024": [],
    "UPSC CSE 2023": [],
    "UPSC CSE 2022": [],
    "UPSC CSE 2021": [],
    "UPSC CSE 2020": [],
    "UPSC CSE 2019": [],
    "UPSC CSE 2018": [],
    "UPSC CSE 2017": [],
    "UPSC CSE 2016": [],
    "UPSC CSE 2015": [],
    "UPSC CSE 2014": [],
    "UPSC CSE 2013": [],
    "UPSC CSE 2012": [],
    "UPSC CSE 2011": [],
  },
  "Modern History PYQ": {
    India_in_the_18th_Century: [],
    Indian_Renaissance_and_Reform_Movements: [],
    Early_Uprising_Against_the_British_and_Revolt_of_1857: [],
    Rise_of_Indian_National_Movement_Moderate_and_Extremists_Phase: [],
    Phases_of_Revolutionary_Nationalism: [],
    The_Beginning_of_Gandhian_Era: [],
    The_National_Movement_in_the_1940s: [],
    Development_of_Press_Education_and_Civil_Services: [],
    Independence_to_Partition: [],
  },
  "Ancient History PYQ": {
    Prehistoric_Period_and_Indus_Valley_Civilisation: [],
    Vedic_and_Later_Vedic_Age: [],
    Mauryan_and_Post_Mauryan_Age: [],
    Gupta_and_Post_Gupta_Age: [],
    Sangam_Age: [],
  },
  "Medieval History PYQ": {
    "Delhi Sultanate (1206 AD to 1526 AD)": [],
    "Mughal Empire (1526 AD to 1761 AD)": [],
    "Provincial Kingdoms in Medieval India": [],
    "Religious movement during medieval period": [],
  },
  "Art and Culture PYQ": {
    "Architecture and Sculpture": [],
    "Literature: Religious and Scientific": [],
    "Performing Arts: Dance, Theatre and Music": [],
    "Visual Arts: Painting, ceramics and drawing": [],
    "Indian Philosophy and Bhakti & Sufi Movements": [],
    "Indian Traditions, Festivals, and Calendars": [],
    Miscellaneous: [],
  },
  "World Geography PYQ": {
    "The Earth and the Universe": [],
    Geomorphology: [],
    Climatology: [],
    Oceanography: [],
    "World Climatic Regions": [],
    "Human and Economic Geography": [],
    "World Map": [],
  },
  "Indian Geography PYQ": {
    "Physiography of India": [],
    "Drainage System of India": [],
    "Indian Climate": [],
    "Natural Vegetation in India": [],
    Soils: [],
    "Mineral and Industries": [],
    "Agriculture in India": [],
    "Indian Map": [],
  },
  "Environment and Ecology PYQ": {
    "Environment & Ecology - Protected Area Network": [],
    "Ecosystem and Ecology": [],
    "Environmental Pollution": [],
    Biodiversity: [],
    "Global Conservation Efforts": [],
    "National Conservation Efforts": [],
    "Climate Change: Causes and Implications": [],
    "Environment, Sustainable Development and General Issues": [],
    Agriculture: [],
  },
  "Polity PYQ": {
    "Historical Background & Making of Indian Constitution": [],
    "Features of the Indian Constitution": [],
    Legislature: [],
    Executive: [],
    Judiciary: [],
    "Local Self Government": [],
    Governance: [],
    "Constitutional and Non-constitutional Bodies": [],
    "Judicial & Quasi-Judicial Bodies": [],
  },
  "IR PYQ": {
    "India's Foreign Policy": [],
    "International Groups and Political Organizations": [],
    "Places in news": [],
  },
  "Economy PYQ": {
    Pillar_1A1_Money_Barter_to_Bitcoins: [],
    Pillar_1B1_Bank_Classification: [],
    Pillar_1B2_NPA_Bad_Loans_BASEL: [],
    Pillar_1C_Sharemarket_Companies_Act: [],
    Pillar_1D1_Insurance_Pension_Financial_inclusion: [],
    Pillar_2A1_Budget_Direct_Taxes: [],
    Pillar_2A2_Budget_Indirect_Taxes_GST: [],
    Pillar_2BC_Finance_Commission_BlackMoney_Subsidies: [],
    Pillar_3A_BoP_CAD_Currency_Exchange: [],
    Pillar_3B_International_Orgs: [],
    Pillar_4A_Sectors_of_Economy_Agriculture: [],
    Pillar_4B_Sectors_MFG_Services_Ease_of_Doing_Biz_IPR_Startup_MSME: [],
    Pillar_4C_NITI_Planning_Commission_FYP_Unemployment: [],
    Pillar_4D_GDP_GNP: [],
    Pillar_4E_Inflation: [],
    Pillar_5A_Infra_Energy: [],
    Pillar_5B_Infra_Transport_Urban_Rural_Communication_Investment_PPP: [],
    Pillar_6A_HRD_Census_Health_Hungery: [],
    Pillar_6B_HRD_Education_and_Skill: [],
    Pillar_6C_HRD_POVERTY: [],
    Pillar_6D_HRD_Weaker_Section_HDI_SDG: [],
    Pillar_7_MicroEconomics: [],
  },
  "Science and Tech PYQ": {
    Biotechnology: [],
    Defence_Technology: [],
    Space_Science: [],
    IT_and_Communication_Technology: [],
    Energy: [],
    Miscellaneous_Science_Tech: [],
    Physics: [],
    Chemistry: [],
    Biology: [],
  },
};
